hotkeys:
  lock/unlock mouse cursor on current monitor: <ctrl>+<alt>+l
  move mouse cursor to next monitor: <ctrl>+<cmd>+<right>
  move mouse cursor to previous monitor: <ctrl>+<cmd>+<left>
  exit: <ctrl>+<f12>
is cross screen ranges by pressed ctrl key: true
monitor numbers:
  DP-2, DP-4, HDMI-0:
    DP-2: 0
    DP-4: 2
    HDMI-0: 1
  DP-4:
    DP-4: 0
# padding: 100  # 100 - for testing on single monitor
padding: 3
